name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

    


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600

  assets:
    - assets/images/Get_started/get_started.png
    - assets/images/Get_started/get.png
    - assets/images/Tutorials/Tutorial_1.png
    - assets/images/Tutorials/Tutorial_1_1.png
    - assets/images/Tutorials/Tutorial_2.png
    - assets/images/Tutorials/Tutorial_1_2.png
    - assets/images/Tutorials/Tutorial_3.png
    - assets/images/Tutorials/Tutorial_1_3.png
    - assets/images/location/accloc.png
    - assets/images/location/rectangle1344.svg
    - assets/images/payment1/currency_rupee.svg
    - assets/images/payment1/rectangle4180.svg
    - assets/images/payment1/visa.png
    - assets/images/payment1/upi.png
    - assets/images/payment1/cash.png
    - assets/images/payment1/rupee.png
    - assets/images/loginas/chef.png    
    - assets/images/loginas/customer.png
    - assets/images/location/arrow.png
    - assets/images/review/biryani.png




    
